version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: magic-pages-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: magic-pages
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data

  books:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: books-microservice
    working_dir: /app
    command: sh -c "NODE_ENV=development nest start books --watch"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: magic-pages
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres123
      DATABASE_SYNC: "true"
      DATABASE_AUTOLOAD: "true"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - postgres
      - minio

  storage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storage-microservice
    working_dir: /app
    command: sh -c "NODE_ENV=development nest start storage --watch"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: magic-pages
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres123
      DATABASE_SYNC: "true"
      DATABASE_AUTOLOAD: "true"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3002:3000"
    depends_on:
      - postgres
      - minio

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    working_dir: /app
    command: sh -c "NODE_ENV=development npm run start:dev"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: magic-pages
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres123
      DATABASE_SYNC: "true"
      DATABASE_AUTOLOAD: "true"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - books
      - storage
      - postgres
