export enum BookGenre {
  FICTION = 'fiction',
  NON_FICTION = 'non_fiction',
  SCIENCE_FICTION = 'science_fiction',
  FANTASY = 'fantasy',
  MYSTERY = 'mystery',
  BIOGRAPHY = 'biography',
  HISTORY = 'history',
  CHILDREN = 'children',
  ROMANCE = 'romance',
  THRILLER = 'thriller',
  SELF_HELP = 'self_help',
  HEALTH = 'health',
  TRAVEL = 'travel',
  RELIGION = 'religion',
  SCIENCE = 'science',
  POETRY = 'poetry',
  PARANORMAL = 'paranormal',
  COMICS = 'comics',
  ART = 'art',
  COOKING = 'cooking',
  EDUCATIONAL = 'educational',
  BUSINESS = 'business',
  PERSONAL_DEVELOPMENT = 'personal_development',
  KIDS = 'kids',
  YOUNG_ADULT = 'young_adult',
  CLASSICS = 'classics',
}
