export enum CartErrorCode {
    CART_NOT_FOUND = 'CART_NOT_FOUND',
    CART_EMPTY = 'CART_EMPTY',
    CART_ITEM_NOT_FOUND = 'CART_ITEM_NOT_FOUND',
    INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
    PAYMENT_FAILED = 'PAYMENT_FAILED',
    PAYMENT_TIMEOUT = 'PAYMENT_TIMEOUT',
    TRANSACTION_ROLLBACK = 'TRANSACTION_ROLLBACK',
    IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
    INVALID_CART_STATUS = 'INVALID_CART_STATUS',
    UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
}
